// Generated by CoffeeScript 1.6.3
(function() {
  describe("Application", function() {
    var app;
    app = null;
    beforeEach(function() {
      var option;
      option = appOptions;
      return app = Ext.application(option);
    });
    afterEach(function() {});
    it("has loaded ExtJS 4", function() {
      expect(typeof Ext).toEqual('object');
      expect(Ext).toBeDefined();
      expect(Ext.getVersion()).toBeTruthy();
      return expect(Ext.getVersion().major).toEqual(4);
    });
    return it("Application Unit", function() {
      return expect(app).toBeDefined();
    });
  });

}).call(this);
